export enum UserRole {
  PLAYER = 'PLAYER',
  ROOT_ADMIN = 'ROOT_ADMIN',
  CONTENT_SPECIALIST = 'CONTENT_SPECIALIST',
  SUPPORT = 'SUPPORT',
}

export enum Difficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
  VERY_HARD = 'VERY_HARD',
}

export enum QuestionStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum GameStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
  EXPIRED = 'EXPIRED',
}

export enum AnswerStatus {
  PENDING = 'PENDING',
  CORRECT = 'CORRECT',
  INCORRECT = 'INCORRECT',
  TIMED_OUT = 'TIMED_OUT',
  REVEALED = 'REVEALED',
}

export enum MatchStatus {
  WAITING = 'WAITING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum CoinTransactionType {
  ANSWER_REWARD = 'ANSWER_REWARD',
  GAME_COMPLETION = 'GAME_COMPLETION',
  MATCH_REWARD = 'MATCH_REWARD',
  MISSION_REWARD = 'MISSION_REWARD',
  QUESTION_SUGGESTION_REWARD = 'QUESTION_SUGGESTION_REWARD',
  SEASON_REWARD = 'SEASON_REWARD',
  PURCHASE = 'PURCHASE',
  SPEND_HINT = 'SPEND_HINT',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}

export enum PrizeType {
  CASH = 'CASH',
  PHYSICAL_ITEM = 'PHYSICAL_ITEM',
  COINS = 'COINS',
  BADGE = 'BADGE',
  PROFILE_BANNER = 'PROFILE_BANNER',
  TITLE = 'TITLE',
}

export enum PrizeClaimStatus {
  PENDING = 'PENDING',
  CONTACTED = 'CONTACTED',
  FULFILLED = 'FULFILLED',
  CANCELLED = 'CANCELLED',
}

export enum ReportTargetType {
  USER = 'USER',
  QUESTION = 'QUESTION',
  QUESTION_SUGGESTION = 'QUESTION_SUGGESTION',
}

export enum ReportStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}
