export enum CoinTransactionType {
  ANSWER_REWARD = 'ANSWER_REWARD',
  GAME_COMPLETION = 'GAME_COMPLETION',
  MATCH_REWARD = 'MATCH_REWARD',
  MISSION_REWARD = 'MISSION_REWARD',
  QUESTION_SUGGESTION_REWARD = 'QUESTION_SUGGESTION_REWARD',
  SEASON_REWARD = 'SEASON_REWARD',
  PURCHASE = 'PURCHASE',
  SPEND_HINT = 'SPEND_HINT',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}

